uint64 timestamp
# Vector 0 head and tail points
uint8 m0_x0    # Tail of vector @ x
uint8 m0_y0    # Tail of vector @ y
uint8 m0_x1    # Head of vector @ x
uint8 m0_y1    # Head of vector @ y

# Vector 1 head and tail points
uint8 m1_x0    # Tail of vector @ x
uint8 m1_y0    # Tail of vector @ y
uint8 m1_x1    # Head of vector @ x
uint8 m1_y1    # Head of vector @ y

# Vector 2 head and tail points
uint8 m2_x0    # Tail of vector @ x
uint8 m2_y0    # Tail of vector @ y
uint8 m2_x1    # Head of vector @ x
uint8 m2_y1    # Head of vector @ y

# Vector 3 head and tail points
uint8 m3_x0    # Tail of vector @ x
uint8 m3_y0    # Tail of vector @ y
uint8 m3_x1    # Head of vector @ x
uint8 m3_y1    # Head of vector @ y

# Vector 4 head and tail points
uint8 m4_x0    # Tail of vector @ x
uint8 m4_y0    # Tail of vector @ y
uint8 m4_x1    # Head of vector @ x
uint8 m4_y1    # Head of vector @ y

# Vector 5 head and tail points
uint8 m5_x0    # Tail of vector @ x
uint8 m5_y0    # Tail of vector @ y
uint8 m5_x1    # Head of vector @ x
uint8 m5_y1    # Head of vector @ y
